import { Space_Grotesk } from "next/font/google";
import "./styles/globals.css";
import Header from "../components/NavBar/Header";
import Footer from "../components/NavBar/Footer";
import { Providers } from "../components/Providers";

const spaceSans = Space_Grotesk({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "NeoFit",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${spaceSans.className} antialiased`}>
                <Providers>
                    <Header />
                    <div className="page container mx-auto max-w-7xl">
                        {children}
                    </div>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
